<?php

namespace App\Exceptions;

use App\Http\Controllers\Api\Webservice\ms;
use App\Http\Controllers\Api\Webservice\ws;
use Exception;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Report or log an exception.
     *
     * @param  \Exception  $exception
     * @return void
     */
    public function report(Exception $exception)
    {
        parent::report($exception);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        return parent::render($request, $exception);
    }

    protected  function  unauthenticated($request, AuthenticationException $exception) {
      if ($request->expectsJson()) {

        /** return response()->json(['error' => 'Unauthenticated.'], 401); */
//        $response = ['status' => 'error','message' => 'You pass invalid token'];

        return ws::r(0, ['data'=>''], 200, ms::MUST_BE_LOGIN);
//        return response()->json($response);

      }

      return redirect()->guest('login');

//      return parent::unauthenticated($request, $exception); // TODO: Change the autogenerated stub
    }
}
